version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    #            target: development
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - dynamodb-local
      - dynamodb-admin

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    #            target: development
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    # command: npm run serve
    command: >
      ash -c 'npm install; npm run dev -- --host'
    # command: sleep infinity # devcontainer のときはこれが必要
    depends_on:
      - dynamodb-local
      - dynamodb-admin

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8100:8100"
    volumes:
      - ./data/dynamodb:/data
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb -port 8100
    networks:
      - default

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    tty: true
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8100
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    networks:
      - default
